# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: my0rg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-python-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-app-assignment-python

# custom:
#   wsgi:
#     app: app.app

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  s3:
    myBucket:
      name: tsanghan-ce6-serverless-s3-bucket

functions:
  hello:
    handler: app.hello
    events:
      - http:
          path: /hello
          method: get
      - s3:
          bucket: myBucket
          event: s3:ObjectCreated:*
      - s3:
          bucket: myBucket
          event: s3:ObjectRemoved:*
  hello2:
    handler: app.hello2
    events:
      - http:
          path: /hello2
          method: get
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures
  hello3:
    handler: app.hello3
    events:
      - http:
          path: /hello3
          method: get
      - sns:
          arn: !Ref SuperTopic
          topicName: MyCustomTopic

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "tsanghan-ce6-Q"
    SuperTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "MyCustomTopic"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
